language: en
pipeline:
- name: SpacyNLP
  model: "en_core_web_md"
- name: SpacyTokenizer
- name: CountVectorsFeaturizer
- name: "CountVectorsFeaturizer"
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 4
- name: RegexFeaturizer
- name: RegexEntityExtractor
- name: DIETClassifier
  epochs: 70
  random_seed: 2
#- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
  retrieval_intent: chitchat
- name: FallbackClassifier
  threshold: 0.6
  ambiguity_threshold: 0.1
policies:
- name: MemoizationPolicy
  max_history: 5
- name: TEDPolicy
  constrain_similarities: true
  model_confidence: linear_norm
  max_history: 5
  epochs: 200
- name: RulePolicy
  core_fallback_threshold: 0.2
